# Please note, Content in this section will be updated based on the actual testrail instance which we will be using as part of Cytel
host: https://archanashivananda.testrail.io/
username: archana.shivananda@cytel.com
password: 7T44mWh7xRkvKBilkhJk-gL5Qlw/VFAWal03JI5vw
project: Automation_TR_Integration